"""Add negative feedback support for tag learning

Revision ID: b6d112c59087
Revises: 409434712f70
Create Date: 2026-01-06 11:23:59.531754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d112c59087'
down_revision: Union[str, Sequence[str], None] = '409434712f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_negative_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('negative_embedding', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['processed_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['email_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'email_id', name='uq_tag_negative_email')
    )
    op.create_index('ix_tag_negative_tag_id', 'tag_negative_examples', ['tag_id'], unique=False)
    
    # SQLite: Skip FK recreation (not supported)
    # op.drop_constraint(None, 'auto_rules', type_='foreignkey')
    # op.create_foreign_key(None, 'auto_rules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('email_tags', sa.Column('negative_embedding', sa.LargeBinary(), nullable=True))
    op.add_column('email_tags', sa.Column('negative_updated_at', sa.DateTime(), nullable=True))
    op.add_column('email_tags', sa.Column('negative_count', sa.Integer(), nullable=True, server_default='0'))
    
    # SQLite: Skip other non-essential schema changes
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_tags', 'negative_count')
    op.drop_column('email_tags', 'negative_updated_at')
    op.drop_column('email_tags', 'negative_embedding')
    op.drop_index('ix_tag_negative_tag_id', table_name='tag_negative_examples')
    op.drop_table('tag_negative_examples')
    # ### end Alembic commands ###
