"""Add encrypted_inline_attachments for CID images

Revision ID: 0490296358e5
Revises: 55a17d1115b6
Create Date: 2026-01-16 15:25:57.382911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0490296358e5'
down_revision: Union[str, Sequence[str], None] = '55a17d1115b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_emails', sa.Column('encrypted_inline_attachments', sa.Text(), nullable=True))
    op.alter_column('raw_emails', 'stable_identifier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_emails', 'stable_identifier',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('raw_emails', 'encrypted_inline_attachments')
    # ### end Alembic commands ###
