"""Add reply style settings table

Revision ID: 28d68dd1186b
Revises: 13710d93ee9c
Create Date: 2026-01-06 19:28:46.552918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d68dd1186b'
down_revision: Union[str, Sequence[str], None] = '13710d93ee9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create reply_style_settings table (FEATURE_REPLY_STYLES)
    op.create_table('reply_style_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style_key', sa.String(length=20), nullable=False),
    sa.Column('address_form', sa.String(length=10), nullable=True),
    sa.Column('salutation', sa.String(length=100), nullable=True),
    sa.Column('closing', sa.String(length=100), nullable=True),
    sa.Column('signature_enabled', sa.Boolean(), nullable=True),
    sa.Column('encrypted_signature_text', sa.Text(), nullable=True),
    sa.Column('encrypted_custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'style_key', name='uq_user_style_key')
    )
    op.create_index('ix_reply_style_user_id', 'reply_style_settings', ['user_id'], unique=False)
    
    # NOTE: Removed auto_rules FK changes (SQLite doesn't support ALTER CONSTRAINT)
    # NOTE: Removed other unrelated column changes (schema drift)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reply_style_user_id', table_name='reply_style_settings')
    op.drop_table('reply_style_settings')
    # ### end Alembic commands ###

