"""add_audit_config_tables

Revision ID: 46a0f5ab4550
Revises: 003181942ae3
Create Date: 2026-01-25 18:00:31.787582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46a0f5ab4550'
down_revision: Union[str, Sequence[str], None] = '003181942ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_list_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('list_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("list_type IN ('trusted_domains', 'safe_patterns', 'important_keywords', 'vip_senders')", name='ck_audit_list_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_audit_list_source')
    )
    op.create_index('idx_audit_list_user', 'audit_list_sources', ['user_id'], unique=False)
    op.create_table('audit_important_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'keyword', name='uq_audit_important_keyword')
    )
    op.create_index('idx_audit_keyword_user', 'audit_important_keywords', ['user_id', 'account_id'], unique=False)
    op.create_table('audit_safe_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("pattern_type IN ('subject', 'sender', 'domain')", name='ck_audit_safe_pattern_type'),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'pattern', 'pattern_type', name='uq_audit_safe_pattern')
    )
    op.create_index('idx_audit_safe_user', 'audit_safe_patterns', ['user_id', 'account_id'], unique=False)
    op.create_table('audit_trusted_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'domain', name='uq_audit_trusted_domain')
    )
    op.create_index('idx_audit_trusted_domain_user', 'audit_trusted_domains', ['user_id', 'account_id'], unique=False)
    op.create_table('audit_vip_senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('sender_pattern', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("pattern_type IN ('exact', 'email_domain', 'domain')", name='ck_audit_vip_pattern_type'),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'sender_pattern', name='uq_audit_vip_sender')
    )
    op.create_index('idx_audit_vip_user', 'audit_vip_senders', ['user_id', 'account_id'], unique=False)
    op.drop_index(op.f('ix_email_tags_learned_embedding_model'), table_name='email_tags')
    op.alter_column('raw_emails', 'processing_warnings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Non-fatal warnings during processing (JSON array)',
               existing_nullable=True)
    op.drop_index(op.f('idx_raw_emails_processing_warnings'), table_name='raw_emails', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_raw_emails_processing_warnings'), 'raw_emails', ['processing_warnings'], unique=False, postgresql_using='gin')
    op.alter_column('raw_emails', 'processing_warnings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Non-fatal warnings during processing (JSON array)',
               existing_nullable=True)
    op.create_index(op.f('ix_email_tags_learned_embedding_model'), 'email_tags', ['learned_embedding_model'], unique=False)
    op.drop_index('idx_audit_vip_user', table_name='audit_vip_senders')
    op.drop_table('audit_vip_senders')
    op.drop_index('idx_audit_trusted_domain_user', table_name='audit_trusted_domains')
    op.drop_table('audit_trusted_domains')
    op.drop_index('idx_audit_safe_user', table_name='audit_safe_patterns')
    op.drop_table('audit_safe_patterns')
    op.drop_index('idx_audit_keyword_user', table_name='audit_important_keywords')
    op.drop_table('audit_important_keywords')
    op.drop_index('idx_audit_list_user', table_name='audit_list_sources')
    op.drop_table('audit_list_sources')
    # ### end Alembic commands ###
