"""PostgreSQL initial schema (baseline)

Revision ID: 55a17d1115b6
Revises: 
Create Date: 2026-01-14 17:31:48.106106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a17d1115b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invited_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('invited_by', sa.String(length=255), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invited_emails_email'), 'invited_emails', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('salt', sa.Text(), nullable=True),
    sa.Column('encrypted_dek', sa.Text(), nullable=True),
    sa.Column('encrypted_master_key', sa.Text(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_embedding_provider', sa.String(length=20), nullable=True),
    sa.Column('preferred_embedding_model', sa.String(length=100), nullable=True),
    sa.Column('preferred_ai_provider', sa.String(length=20), nullable=True),
    sa.Column('preferred_ai_model', sa.String(length=100), nullable=True),
    sa.Column('preferred_ai_provider_optimize', sa.String(length=20), nullable=True),
    sa.Column('preferred_ai_model_optimize', sa.String(length=100), nullable=True),
    sa.Column('fetch_mails_per_folder', sa.Integer(), nullable=True),
    sa.Column('fetch_max_total', sa.Integer(), nullable=True),
    sa.Column('fetch_use_delta_sync', sa.Boolean(), nullable=True),
    sa.Column('imap_diagnostics_enabled', sa.Boolean(), nullable=True),
    sa.Column('enable_tag_suggestion_queue', sa.Boolean(), nullable=True),
    sa.Column('enable_auto_assignment', sa.Boolean(), nullable=True),
    sa.Column('urgency_booster_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auto_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('times_triggered', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_rules_is_active'), 'auto_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_auto_rules_priority'), 'auto_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_auto_rules_user_id'), 'auto_rules', ['user_id'], unique=False)
    op.create_table('email_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learned_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(), nullable=True),
    sa.Column('negative_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('negative_updated_at', sa.DateTime(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_tag_name')
    )
    op.create_table('mail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('encrypted_imap_server', sa.Text(), nullable=True),
    sa.Column('imap_server_hash', sa.String(length=64), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('encrypted_imap_username', sa.Text(), nullable=True),
    sa.Column('imap_username_hash', sa.String(length=64), nullable=True),
    sa.Column('encrypted_imap_password', sa.Text(), nullable=True),
    sa.Column('imap_encryption', sa.String(length=50), nullable=True),
    sa.Column('encrypted_smtp_server', sa.Text(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('encrypted_smtp_username', sa.Text(), nullable=True),
    sa.Column('encrypted_smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_encryption', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('encrypted_oauth_token', sa.Text(), nullable=True),
    sa.Column('encrypted_oauth_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_expires_at', sa.DateTime(), nullable=True),
    sa.Column('encrypted_pop3_server', sa.Text(), nullable=True),
    sa.Column('pop3_port', sa.Integer(), nullable=True),
    sa.Column('encrypted_pop3_username', sa.Text(), nullable=True),
    sa.Column('encrypted_pop3_password', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('initial_sync_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_since_date', sa.Date(), nullable=True),
    sa.Column('fetch_unseen_only', sa.Boolean(), nullable=True),
    sa.Column('fetch_include_folders', sa.Text(), nullable=True),
    sa.Column('fetch_exclude_folders', sa.Text(), nullable=True),
    sa.Column('folder_uidvalidity', sa.Text(), nullable=True),
    sa.Column('detected_provider', sa.String(length=50), nullable=True),
    sa.Column('server_name', sa.String(length=255), nullable=True),
    sa.Column('server_version', sa.String(length=100), nullable=True),
    sa.Column('signature_enabled', sa.Boolean(), nullable=True),
    sa.Column('encrypted_signature_text', sa.Text(), nullable=True),
    sa.Column('urgency_booster_enabled', sa.Boolean(), nullable=False),
    sa.Column('enable_ai_analysis_on_fetch', sa.Boolean(), nullable=False),
    sa.Column('last_server_sync_at', sa.DateTime(), nullable=True),
    sa.Column('anonymize_with_spacy', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_anon_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_original_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_accounts_imap_server_hash'), 'mail_accounts', ['imap_server_hash'], unique=False)
    op.create_index(op.f('ix_mail_accounts_imap_username_hash'), 'mail_accounts', ['imap_username_hash'], unique=False)
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('reply_style_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style_key', sa.String(length=20), nullable=False),
    sa.Column('address_form', sa.String(length=10), nullable=True),
    sa.Column('salutation', sa.String(length=100), nullable=True),
    sa.Column('closing', sa.String(length=100), nullable=True),
    sa.Column('signature_enabled', sa.Boolean(), nullable=True),
    sa.Column('encrypted_signature_text', sa.Text(), nullable=True),
    sa.Column('encrypted_custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'style_key', name='uq_user_style_key')
    )
    op.create_index('ix_reply_style_user_id', 'reply_style_settings', ['user_id'], unique=False)
    op.create_table('sender_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_newsletter', sa.Boolean(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('correction_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sender_hash', name='uq_user_sender_pattern')
    )
    op.create_index(op.f('ix_sender_patterns_sender_hash'), 'sender_patterns', ['sender_hash'], unique=False)
    op.create_index(op.f('ix_sender_patterns_user_id'), 'sender_patterns', ['user_id'], unique=False)
    op.create_table('service_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('encrypted_dek', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('email_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('imap_path', sa.String(length=500), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_special_folder', sa.Boolean(), nullable=True),
    sa.Column('special_folder_type', sa.String(length=50), nullable=True),
    sa.Column('display_name_localized', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mail_account_id', 'imap_path', name='uq_email_folders_path')
    )
    op.create_index(op.f('ix_email_folders_mail_account_id'), 'email_folders', ['mail_account_id'], unique=False)
    op.create_index(op.f('ix_email_folders_user_id'), 'email_folders', ['user_id'], unique=False)
    op.create_table('raw_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail_account_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_sender', sa.Text(), nullable=False),
    sa.Column('encrypted_subject', sa.Text(), nullable=True),
    sa.Column('encrypted_body', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('imap_uid', sa.Integer(), nullable=True),
    sa.Column('imap_folder', sa.String(length=200), nullable=False),
    sa.Column('imap_uidvalidity', sa.Integer(), nullable=True),
    sa.Column('imap_flags', sa.String(length=500), nullable=True),
    sa.Column('imap_last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('encrypted_in_reply_to', sa.Text(), nullable=True),
    sa.Column('parent_uid', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('imap_is_seen', sa.Boolean(), nullable=True),
    sa.Column('imap_is_answered', sa.Boolean(), nullable=True),
    sa.Column('imap_is_flagged', sa.Boolean(), nullable=True),
    sa.Column('imap_is_deleted', sa.Boolean(), nullable=True),
    sa.Column('imap_is_draft', sa.Boolean(), nullable=True),
    sa.Column('encrypted_to', sa.Text(), nullable=True),
    sa.Column('encrypted_cc', sa.Text(), nullable=True),
    sa.Column('encrypted_bcc', sa.Text(), nullable=True),
    sa.Column('encrypted_reply_to', sa.Text(), nullable=True),
    sa.Column('message_size', sa.Integer(), nullable=True),
    sa.Column('encrypted_references', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('charset', sa.String(length=50), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('last_flag_sync_at', sa.DateTime(), nullable=True),
    sa.Column('email_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=50), nullable=True),
    sa.Column('embedding_generated_at', sa.DateTime(), nullable=True),
    sa.Column('auto_rules_processed', sa.Boolean(), nullable=False),
    sa.Column('encrypted_subject_sanitized', sa.Text(), nullable=True),
    sa.Column('encrypted_body_sanitized', sa.Text(), nullable=True),
    sa.Column('sanitization_level', sa.Integer(), nullable=True),
    sa.Column('sanitization_time_ms', sa.Float(), nullable=True),
    sa.Column('sanitization_entities_count', sa.Integer(), nullable=True),
    sa.Column('encrypted_entity_map', sa.Text(), nullable=True),
    sa.Column('stable_identifier', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mail_account_id', 'imap_folder', 'imap_uidvalidity', 'imap_uid', name='uq_raw_emails_rfc_unique')
    )
    op.create_index('ix_raw_emails_account_folder_uid', 'raw_emails', ['mail_account_id', 'imap_folder', 'imap_uid'], unique=False)
    op.create_index(op.f('ix_raw_emails_auto_rules_processed'), 'raw_emails', ['auto_rules_processed'], unique=False)
    op.create_index(op.f('ix_raw_emails_content_hash'), 'raw_emails', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_emails_imap_is_answered'), 'raw_emails', ['imap_is_answered'], unique=False)
    op.create_index(op.f('ix_raw_emails_imap_is_flagged'), 'raw_emails', ['imap_is_flagged'], unique=False)
    op.create_index(op.f('ix_raw_emails_imap_is_seen'), 'raw_emails', ['imap_is_seen'], unique=False)
    op.create_index(op.f('ix_raw_emails_imap_uid'), 'raw_emails', ['imap_uid'], unique=False)
    op.create_index(op.f('ix_raw_emails_imap_uidvalidity'), 'raw_emails', ['imap_uidvalidity'], unique=False)
    op.create_index(op.f('ix_raw_emails_mail_account_id'), 'raw_emails', ['mail_account_id'], unique=False)
    op.create_index(op.f('ix_raw_emails_message_id'), 'raw_emails', ['message_id'], unique=False)
    op.create_index(op.f('ix_raw_emails_parent_uid'), 'raw_emails', ['parent_uid'], unique=False)
    op.create_index(op.f('ix_raw_emails_received_at'), 'raw_emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_emails_stable_identifier'), 'raw_emails', ['stable_identifier'], unique=False)
    op.create_index(op.f('ix_raw_emails_thread_id'), 'raw_emails', ['thread_id'], unique=False)
    op.create_index(op.f('ix_raw_emails_user_id'), 'raw_emails', ['user_id'], unique=False)
    op.create_table('spacy_keyword_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('set_type', sa.String(length=50), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('points_per_match', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'set_type', name='uq_keywords_user_account_type')
    )
    op.create_index('ix_spacy_keywords_user_account', 'spacy_keyword_sets', ['user_id', 'account_id', 'set_type'], unique=False)
    op.create_table('spacy_scoring_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('imperative_weight', sa.Integer(), nullable=False),
    sa.Column('deadline_weight', sa.Integer(), nullable=False),
    sa.Column('keyword_weight', sa.Integer(), nullable=False),
    sa.Column('vip_weight', sa.Integer(), nullable=False),
    sa.Column('question_threshold', sa.Integer(), nullable=False),
    sa.Column('negation_sensitivity', sa.Integer(), nullable=False),
    sa.Column('spacy_weight_initial', sa.Integer(), nullable=False),
    sa.Column('spacy_weight_learning', sa.Integer(), nullable=False),
    sa.Column('spacy_weight_trained', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_scoring_user_account')
    )
    op.create_index('idx_spacy_config_account', 'spacy_scoring_config', ['account_id'], unique=False)
    op.create_table('spacy_user_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'domain', name='uq_spacy_user_domain')
    )
    op.create_index('idx_spacy_domains_account', 'spacy_user_domains', ['account_id'], unique=False)
    op.create_table('spacy_vip_senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('sender_pattern', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('importance_boost', sa.Integer(), nullable=False),
    sa.Column('urgency_boost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sender_pattern', 'account_id', name='uq_vip_user_pattern_account')
    )
    op.create_index('ix_spacy_vip_user_account', 'spacy_vip_senders', ['user_id', 'account_id'], unique=False)
    op.create_table('trusted_senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('sender_pattern', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('use_urgency_booster', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sender_pattern', name='uq_user_sender')
    )
    op.create_table('mail_server_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail_account_id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('uidvalidity', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('envelope_from', sa.Text(), nullable=True),
    sa.Column('envelope_subject', sa.Text(), nullable=True),
    sa.Column('envelope_date', sa.DateTime(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('raw_email_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], ),
    sa.ForeignKeyConstraint(['raw_email_id'], ['raw_emails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mail_account_id', 'folder', 'uid', 'uidvalidity', name='uq_server_state_folder_uid')
    )
    op.create_index('idx_server_state_hash', 'mail_server_state', ['user_id', 'mail_account_id', 'content_hash'], unique=False)
    op.create_index('idx_server_state_msgid', 'mail_server_state', ['user_id', 'mail_account_id', 'message_id'], unique=False)
    op.create_index('idx_server_state_not_fetched', 'mail_server_state', ['user_id', 'mail_account_id', 'raw_email_id'], unique=False)
    op.create_table('processed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_email_id', sa.Integer(), nullable=False),
    sa.Column('dringlichkeit', sa.Integer(), nullable=True),
    sa.Column('wichtigkeit', sa.Integer(), nullable=True),
    sa.Column('kategorie_aktion', sa.String(length=50), nullable=True),
    sa.Column('spam_flag', sa.Boolean(), nullable=True),
    sa.Column('encrypted_summary_de', sa.Text(), nullable=True),
    sa.Column('encrypted_text_de', sa.Text(), nullable=True),
    sa.Column('encrypted_tags', sa.Text(), nullable=True),
    sa.Column('encrypted_correction_note', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('matrix_x', sa.Integer(), nullable=True),
    sa.Column('matrix_y', sa.Integer(), nullable=True),
    sa.Column('farbe', sa.String(length=10), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('rebase_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('optimization_status', sa.String(length=20), nullable=True),
    sa.Column('optimization_tried_at', sa.DateTime(), nullable=True),
    sa.Column('optimization_completed_at', sa.DateTime(), nullable=True),
    sa.Column('base_provider', sa.String(length=50), nullable=True),
    sa.Column('base_model', sa.String(length=100), nullable=True),
    sa.Column('optimize_provider', sa.String(length=50), nullable=True),
    sa.Column('optimize_model', sa.String(length=100), nullable=True),
    sa.Column('analysis_method', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('optimize_dringlichkeit', sa.Integer(), nullable=True),
    sa.Column('optimize_wichtigkeit', sa.Integer(), nullable=True),
    sa.Column('optimize_kategorie_aktion', sa.String(length=50), nullable=True),
    sa.Column('optimize_spam_flag', sa.Boolean(), nullable=True),
    sa.Column('optimize_encrypted_summary_de', sa.Text(), nullable=True),
    sa.Column('optimize_encrypted_text_de', sa.Text(), nullable=True),
    sa.Column('optimize_encrypted_tags', sa.Text(), nullable=True),
    sa.Column('optimize_score', sa.Integer(), nullable=True),
    sa.Column('optimize_matrix_x', sa.Integer(), nullable=True),
    sa.Column('optimize_matrix_y', sa.Integer(), nullable=True),
    sa.Column('optimize_farbe', sa.String(length=10), nullable=True),
    sa.Column('optimize_confidence', sa.Float(), nullable=True),
    sa.Column('user_override_dringlichkeit', sa.Integer(), nullable=True),
    sa.Column('user_override_wichtigkeit', sa.Integer(), nullable=True),
    sa.Column('user_override_kategorie', sa.String(length=50), nullable=True),
    sa.Column('user_override_spam_flag', sa.Boolean(), nullable=True),
    sa.Column('user_override_tags', sa.String(length=500), nullable=True),
    sa.Column('correction_timestamp', sa.DateTime(), nullable=True),
    sa.Column('imap_flags_at_processing', sa.String(length=500), nullable=True),
    sa.Column('was_seen_at_processing', sa.Boolean(), nullable=True),
    sa.Column('was_answered_at_processing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['raw_email_id'], ['raw_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_emails_raw_email_id'), 'processed_emails', ['raw_email_id'], unique=True)
    op.create_table('email_tag_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('auto_assigned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['processed_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['email_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', 'tag_id', name='uq_email_tag')
    )
    op.create_table('rule_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail_account_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('processed_email_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_email_id'], ['processed_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['auto_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rule_exec_account_time', 'rule_execution_logs', ['mail_account_id', 'executed_at'], unique=False)
    op.create_index('idx_rule_exec_email', 'rule_execution_logs', ['processed_email_id'], unique=False)
    op.create_index('idx_rule_exec_rule', 'rule_execution_logs', ['rule_id'], unique=False)
    op.create_table('tag_negative_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('negative_embedding', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['processed_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['email_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'email_id', name='uq_tag_negative_email')
    )
    op.create_index('ix_tag_negative_tag_id', 'tag_negative_examples', ['tag_id'], unique=False)
    op.create_table('tag_suggestion_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suggested_name', sa.String(length=50), nullable=False),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merged_into_tag_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_tag_id'], ['email_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_email_id'], ['processed_emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'suggested_name', name='uq_user_pending_suggestion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_suggestion_queue')
    op.drop_index('ix_tag_negative_tag_id', table_name='tag_negative_examples')
    op.drop_table('tag_negative_examples')
    op.drop_index('idx_rule_exec_rule', table_name='rule_execution_logs')
    op.drop_index('idx_rule_exec_email', table_name='rule_execution_logs')
    op.drop_index('idx_rule_exec_account_time', table_name='rule_execution_logs')
    op.drop_table('rule_execution_logs')
    op.drop_table('email_tag_assignments')
    op.drop_index(op.f('ix_processed_emails_raw_email_id'), table_name='processed_emails')
    op.drop_table('processed_emails')
    op.drop_index('idx_server_state_not_fetched', table_name='mail_server_state')
    op.drop_index('idx_server_state_msgid', table_name='mail_server_state')
    op.drop_index('idx_server_state_hash', table_name='mail_server_state')
    op.drop_table('mail_server_state')
    op.drop_table('trusted_senders')
    op.drop_index('ix_spacy_vip_user_account', table_name='spacy_vip_senders')
    op.drop_table('spacy_vip_senders')
    op.drop_index('idx_spacy_domains_account', table_name='spacy_user_domains')
    op.drop_table('spacy_user_domains')
    op.drop_index('idx_spacy_config_account', table_name='spacy_scoring_config')
    op.drop_table('spacy_scoring_config')
    op.drop_index('ix_spacy_keywords_user_account', table_name='spacy_keyword_sets')
    op.drop_table('spacy_keyword_sets')
    op.drop_index(op.f('ix_raw_emails_user_id'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_thread_id'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_stable_identifier'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_received_at'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_parent_uid'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_message_id'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_mail_account_id'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_imap_uidvalidity'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_imap_uid'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_imap_is_seen'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_imap_is_flagged'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_imap_is_answered'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_content_hash'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_auto_rules_processed'), table_name='raw_emails')
    op.drop_index('ix_raw_emails_account_folder_uid', table_name='raw_emails')
    op.drop_table('raw_emails')
    op.drop_index(op.f('ix_email_folders_user_id'), table_name='email_folders')
    op.drop_index(op.f('ix_email_folders_mail_account_id'), table_name='email_folders')
    op.drop_table('email_folders')
    op.drop_table('service_tokens')
    op.drop_index(op.f('ix_sender_patterns_user_id'), table_name='sender_patterns')
    op.drop_index(op.f('ix_sender_patterns_sender_hash'), table_name='sender_patterns')
    op.drop_table('sender_patterns')
    op.drop_index('ix_reply_style_user_id', table_name='reply_style_settings')
    op.drop_table('reply_style_settings')
    op.drop_table('recovery_codes')
    op.drop_index(op.f('ix_mail_accounts_imap_username_hash'), table_name='mail_accounts')
    op.drop_index(op.f('ix_mail_accounts_imap_server_hash'), table_name='mail_accounts')
    op.drop_table('mail_accounts')
    op.drop_table('email_tags')
    op.drop_index(op.f('ix_auto_rules_user_id'), table_name='auto_rules')
    op.drop_index(op.f('ix_auto_rules_priority'), table_name='auto_rules')
    op.drop_index(op.f('ix_auto_rules_is_active'), table_name='auto_rules')
    op.drop_table('auto_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invited_emails_email'), table_name='invited_emails')
    op.drop_table('invited_emails')
    # ### end Alembic commands ###
