"""add auto-translation fields to raw_emails

Revision ID: 6b293d67c016
Revises: d0b8c96df420
Create Date: 2026-01-23 13:48:42.209623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b293d67c016'
down_revision: Union[str, Sequence[str], None] = 'd0b8c96df420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_emails', sa.Column('detected_language', sa.String(length=5), nullable=True))
    op.add_column('raw_emails', sa.Column('encrypted_translation_de', sa.Text(), nullable=True))
    op.add_column('raw_emails', sa.Column('translation_engine', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_raw_emails_detected_language'), 'raw_emails', ['detected_language'], unique=False)
    op.alter_column('users', 'enable_auto_fetch',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'enable_auto_fetch',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_raw_emails_detected_language'), table_name='raw_emails')
    op.drop_column('raw_emails', 'translation_engine')
    op.drop_column('raw_emails', 'encrypted_translation_de')
    op.drop_column('raw_emails', 'detected_language')
    # ### end Alembic commands ###
