"""add_encrypted_dek_column

Revision ID: 7ee0bae8b1c2
Revises: p1p2p3p4p5p6
Create Date: 2025-12-27 00:25:48.246402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee0bae8b1c2'
down_revision: Union[str, Sequence[str], None] = 'p1p2p3p4p5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_dek', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_dek')
    # ### end Alembic commands ###
