"""increase_salt_field_length

Revision ID: 9347aa16b0a6
Revises: 7ee0bae8b1c2
Create Date: 2025-12-27 00:35:21.483253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9347aa16b0a6'
down_revision: Union[str, Sequence[str], None] = '7ee0bae8b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - SQLite workaround für ALTER COLUMN TYPE."""
    # SQLite: Tabelle neu erstellen mit neuer Feldlänge
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salt',
                   existing_type=sa.VARCHAR(length=32),
                   type_=sa.String(length=64),
                   existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
