"""change_salt_to_text

Revision ID: a8d9d8855a82
Revises: 9347aa16b0a6
Create Date: 2025-12-27 01:06:06.984744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d9d8855a82'
down_revision: Union[str, Sequence[str], None] = '9347aa16b0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - SQLite workaround mit batch_alter_table."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salt',
                   existing_type=sa.VARCHAR(length=64),
                   type_=sa.Text(),
                   existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
