"""Add EmailAttachment table for classic attachments

Revision ID: df80ed2daa74
Revises: 0490296358e5
Create Date: 2026-01-17 14:38:37.032028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df80ed2daa74'
down_revision: Union[str, Sequence[str], None] = '0490296358e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('encrypted_data', sa.Text(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_email_id'], ['raw_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_attachments_raw_email_id', 'email_attachments', ['raw_email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_attachments_raw_email_id', table_name='email_attachments')
    op.drop_table('email_attachments')
    # ### end Alembic commands ###
